-- Insertar plagas colombianas con sus cultivos asociados
INSERT INTO plaga (nombre_plaga, tipo_plaga, cultivos_afectados) VALUES
('Mosca blanca','Insecto','Tomate,Pimentón,Fresa,Frijol,Papa,Brócoli,Lechuga'),
('Tizón tardío','Hongo','Tomate,Papa,Pimentón'),
('Minador de hoja','Insecto','Tomate,Papa,Café,Cítricos,Limón,Naranja,Mandarina'),
('Ácaros','Ácaro','Tomate,Fresa,Aguacate,Mango,Palma africana,Flores'),
('Trips','Insecto','Tomate,Aguacate,Mango,Fresa,Flores,Cebolla,Pimentón'),
('Alternaria','Hongo','Tomate,Papa,Zanahoria,Brócoli'),
('Gusano del fruto','Insecto','Tomate,Pimentón,Maíz,Frijol'),
('Broca del café','Insecto','Café'),
('Roya del café','Hongo','Café'),
('Antracnosis','Hongo','Café,Aguacate,Mango,Fresa,Mora,Gulupa,Maracuyá'),
('Polilla guatemalteca','Insecto','Papa'),
('Gusano blanco de la papa','Insecto','Papa'),
('Sigatoka negra','Hongo','Plátano,Banano'),
('Moko del plátano','Bacteria','Plátano,Banano'),
('Picudo negro','Insecto','Plátano,Banano'),
('Gusano cogollero','Insecto','Maíz,Sorgo,Arroz,Frijol'),
('Phytophthora','Hongo','Aguacate,Papa,Tomate,Cítricos'),
('Barrenador del hueso','Insecto','Aguacate'),
('Mosca de la fruta','Insecto','Mango,Aguacate,Cítricos,Naranja,Limón,Mandarina,Maracuyá,Guayaba,Mora'),
('Cochonilla harinosa','Insecto','Cítricos,Naranja,Limón,Mandarina,Aguacate,Vid,Café'),
('Pulgón','Insecto','Café,Cítricos,Naranja,Limón,Fresa,Papa,Tomate,Brócoli,Lechuga,Frijol'),
('Botrytis','Hongo','Fresa,Vid,Mora,Gulupa,Flores,Brócoli'),
('Fusarium','Hongo','Tomate,Papa,Plátano,Banano,Maíz,Frijol,Fresa'),
('Nematodos','Nematodo','Tomate,Papa,Banano,Plátano,Café,Zanahoria,Arroz,Fresa'),
('Pudrición del cogollo','Hongo','Palma africana'),
('Piricularia','Hongo','Arroz'),
('Sogata del arroz','Insecto','Arroz'),
('Sigatoka amarilla','Hongo','Plátano,Banano'),
('Moniliasis del cacao','Hongo','Cacao'),
('Escoba de bruja','Hongo','Cacao'),
('Áfido del cacao','Insecto','Cacao'),
('Diatraea','Insecto','Caña de azúcar,Maíz,Sorgo'),
('Caracol','Molusco','Arroz,Lechuga,Fresa'),
('Noctua del suelo','Insecto','Papa,Tomate,Maíz,Zanahoria,Frijol'),
('Marchitamiento bacteriano','Bacteria','Tomate,Papa,Pimentón');
